
package wcf.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import cn.emagsoftware.utils.CommonUtils;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Internal", targetNamespace = "http://tempuri.org/")
public class Internal
    extends Service
{

    private final static URL INTERNAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(wcf.client.Internal.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = wcf.client.Internal.class.getResource(".");
            url = new URL(baseUrl, CommonUtils.getPropertiesValue("config","wcf.wsdl.location"));
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.17.104:7280/XfbInternal/mex?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (Exception ex) {
        	logger.warning(ex.getMessage());
        }
        INTERNAL_WSDL_LOCATION = url;
    }

    public Internal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Internal() {
        super(INTERNAL_WSDL_LOCATION, new QName("http://tempuri.org/", "Internal"));
    }

    /**
     * 
     * @return
     *     returns IInternal
     */
    @WebEndpoint(name = "BasicHttpBinding_IInternal")
    public IInternal getBasicHttpBindingIInternal() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IInternal"), IInternal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IInternal
     */
    @WebEndpoint(name = "BasicHttpBinding_IInternal")
    public IInternal getBasicHttpBindingIInternal(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IInternal"), IInternal.class, features);
    }

}
