package cn.tyiti.xfb.webservice.blacklist;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * creditInfoExtWebservice service = new creditInfoExtWebservice();
 * ICreditInfoExtWebservice portType = service.getCreditInfoExtWebservicePort();
 * portType.queryServiceItemByCode(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "creditInfoExtWebservice", targetNamespace = "http://webservice.internetfinance.com/", wsdlLocation = "http://121.41.87.97:8081/internetfinance/webservice/creditInfoExt?wsdl")
public class CreditInfoExtWebservice extends Service {

	private final static URL CREDITINFOEXTWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.tyiti.xfb.webservice.blacklist.CreditInfoExtWebservice.class
					.getName());
	
	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.tyiti.xfb.webservice.blacklist.CreditInfoExtWebservice.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://121.41.87.97:8081/internetfinance/webservice/creditInfoExt?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://121.41.87.97:8081/internetfinance/webservice/creditInfoExt?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CREDITINFOEXTWEBSERVICE_WSDL_LOCATION = url;
	}

	public CreditInfoExtWebservice(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CreditInfoExtWebservice() {
		super(CREDITINFOEXTWEBSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.internetfinance.com/",
				"creditInfoExtWebservice"));
	}

	/**
	 * 
	 * @return returns ICreditInfoExtWebservice
	 */
	@WebEndpoint(name = "CreditInfoExtWebservicePort")
	public ICreditInfoExtWebservice getCreditInfoExtWebservicePort() {
		return super.getPort(new QName(
				"http://webservice.internetfinance.com/",
				"CreditInfoExtWebservicePort"), ICreditInfoExtWebservice.class);
	}

}
