
package wcf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IInternal", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IInternal {


    /**
     * 
     * @param id
     * @param ln
     * @param name
     * @param pw
     * @param code
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IInternal/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "wcf.client.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.RegisterResponse")
    public Boolean register(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "ln", targetNamespace = "http://tempuri.org/")
        String ln,
        @WebParam(name = "pw", targetNamespace = "http://tempuri.org/")
        String pw,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id);

    /**
     * 
     * @param ln
     * @param code
     * @param type
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetMemberType", action = "http://tempuri.org/IInternal/SetMemberType")
    @WebResult(name = "SetMemberTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetMemberType", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetMemberType")
    @ResponseWrapper(localName = "SetMemberTypeResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetMemberTypeResponse")
    public Boolean setMemberType(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "ln", targetNamespace = "http://tempuri.org/")
        String ln,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        Integer type);

    /**
     * 
     * @param ln
     * @param pw
     * @param code
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetPassword", action = "http://tempuri.org/IInternal/SetPassword")
    @WebResult(name = "SetPasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetPassword", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetPassword")
    @ResponseWrapper(localName = "SetPasswordResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetPasswordResponse")
    public Boolean setPassword(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "ln", targetNamespace = "http://tempuri.org/")
        String ln,
        @WebParam(name = "pw", targetNamespace = "http://tempuri.org/")
        String pw);

    /**
     * 
     * @param ln
     * @param validity
     * @param code
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetUserStatus", action = "http://tempuri.org/IInternal/SetUserStatus")
    @WebResult(name = "SetUserStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetUserStatus", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetUserStatus")
    @ResponseWrapper(localName = "SetUserStatusResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetUserStatusResponse")
    public Boolean setUserStatus(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "ln", targetNamespace = "http://tempuri.org/")
        String ln,
        @WebParam(name = "validity", targetNamespace = "http://tempuri.org/")
        Boolean validity);

    /**
     * 
     * @param ln
     * @param name
     * @param number
     * @param bank
     * @param code
     * @param type
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddBankCard", action = "http://tempuri.org/IInternal/AddBankCard")
    @WebResult(name = "AddBankCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddBankCard", targetNamespace = "http://tempuri.org/", className = "wcf.client.AddBankCard")
    @ResponseWrapper(localName = "AddBankCardResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.AddBankCardResponse")
    public Boolean addBankCard(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "ln", targetNamespace = "http://tempuri.org/")
        String ln,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "bank", targetNamespace = "http://tempuri.org/")
        String bank,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number);

    /**
     * 
     * @param id
     * @param status
     * @param pay
     * @param paycode
     * @param code
     * @param billno
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetBillStatus", action = "http://tempuri.org/IInternal/SetBillStatus")
    @WebResult(name = "SetBillStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetBillStatus", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetBillStatus")
    @ResponseWrapper(localName = "SetBillStatusResponse", targetNamespace = "http://tempuri.org/", className = "wcf.client.SetBillStatusResponse")
    public Boolean setBillStatus(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id,
        @WebParam(name = "billno", targetNamespace = "http://tempuri.org/")
        String billno,
        @WebParam(name = "pay", targetNamespace = "http://tempuri.org/")
        Integer pay,
        @WebParam(name = "paycode", targetNamespace = "http://tempuri.org/")
        String paycode,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        Integer status);

}
